services:
  plausible_db:
    # Plausible v2.1.0 was tested against PostgreSQL versions 15 and 16
    container_name: plausible_postgresql
    image: postgres:16-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - fuzzylogic

  plausible_events_db:
    container_name: plausible_clickhouse
    image: clickhouse/clickhouse-server:24.3.3.102-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - event-logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - fuzzylogic

  plausible:
    container_name: plausible
    image: ghcr.io/plausible/community-edition:v2.1.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    ports:
      - 8000
    env_file:
      - .env
    networks:
      - fuzzylogic

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  event-logs:
    driver: local

networks:
  fuzzylogic:
    external: true
